name: Build
on:
  push:
    branches: [master, Swiper6, Swiper7, Swiper8]
  pull_request:
    branches: [master, Swiper6, Swiper7, Swiper8]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.2
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build:prod
      - name: Debug npm token
        run: |
          echo "== Check NODE_AUTH_TOKEN existence =="
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "NODE_AUTH_TOKEN is EMPTY ❌"
            exit 1
          else
            echo "NODE_AUTH_TOKEN is set ✅"
            # In ra độ dài token thôi, tránh lộ token
            echo "Token length: ${#NODE_AUTH_TOKEN}"
          fi

          echo "== Check npm config =="
          npm config list
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run release
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
